project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Miscellaneous Tutorials"
  favicon: content/images/logo_lyon.png
  repo-url: https://github.com/njlyon0/teach_tutorials
  repo-actions: [issue]
  navbar:
    background: primary
    right: 
      - text: "People"
        menu:
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
      - icon: github
        href: https://github.com/njlyon0/teach_tutorials
  sidebar: 
    style: docked
    collapse-level: 2
    contents:
      - section: "Data Science"
        contents:
          - text: "Statistics"
            href: content/statistics.qmd
          - text: "Version Control"
            href: content/version-control.qmd
      - section: "Team Science"
        contents: 
          - text: "Facilitation"
            href: content/facilitation.qmd
  page-footer: 
    center: "Copyright &copy; 2026, Nick J Lyon"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    theme:
      light: _extensions/njlyon0/lyon_theme/lyon_light.scss
      dark: _extensions/njlyon0/lyon_theme/lyon_dark.scss
    mainfont: Open Sans
